// Code generated by protoc-gen-go. DO NOT EDIT.
// source: placementcontroller.proto

package placementcontroller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceRequest struct {
	AppContext           string   `protobuf:"bytes,1,opt,name=appContext,proto3" json:"appContext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceRequest) Reset()         { *m = ResourceRequest{} }
func (m *ResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ResourceRequest) ProtoMessage()    {}
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_placementcontroller_9af73c79db95c120, []int{0}
}
func (m *ResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRequest.Unmarshal(m, b)
}
func (m *ResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRequest.Marshal(b, m, deterministic)
}
func (dst *ResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRequest.Merge(dst, src)
}
func (m *ResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ResourceRequest.Size(m)
}
func (m *ResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRequest proto.InternalMessageInfo

func (m *ResourceRequest) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

type ResourceResponse struct {
	AppContext           string   `protobuf:"bytes,1,opt,name=appContext,proto3" json:"appContext,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceResponse) Reset()         { *m = ResourceResponse{} }
func (m *ResourceResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceResponse) ProtoMessage()    {}
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_placementcontroller_9af73c79db95c120, []int{1}
}
func (m *ResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceResponse.Unmarshal(m, b)
}
func (m *ResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceResponse.Marshal(b, m, deterministic)
}
func (dst *ResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceResponse.Merge(dst, src)
}
func (m *ResourceResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceResponse.Size(m)
}
func (m *ResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceResponse proto.InternalMessageInfo

func (m *ResourceResponse) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

func (m *ResourceResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ResourceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourceRequest)(nil), "ResourceRequest")
	proto.RegisterType((*ResourceResponse)(nil), "ResourceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlacementControllerClient is the client API for PlacementController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlacementControllerClient interface {
	FilterClusters(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
}

type placementControllerClient struct {
	cc *grpc.ClientConn
}

func NewPlacementControllerClient(cc *grpc.ClientConn) PlacementControllerClient {
	return &placementControllerClient{cc}
}

func (c *placementControllerClient) FilterClusters(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, "/PlacementController/FilterClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacementControllerServer is the server API for PlacementController service.
type PlacementControllerServer interface {
	FilterClusters(context.Context, *ResourceRequest) (*ResourceResponse, error)
}

func RegisterPlacementControllerServer(s *grpc.Server, srv PlacementControllerServer) {
	s.RegisterService(&_PlacementController_serviceDesc, srv)
}

func _PlacementController_FilterClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementControllerServer).FilterClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlacementController/FilterClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementControllerServer).FilterClusters(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlacementController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PlacementController",
	HandlerType: (*PlacementControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilterClusters",
			Handler:    _PlacementController_FilterClusters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "placementcontroller.proto",
}

func init() {
	proto.RegisterFile("placementcontroller.proto", fileDescriptor_placementcontroller_9af73c79db95c120)
}

var fileDescriptor_placementcontroller_9af73c79db95c120 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x14, 0x45, 0xa7, 0x33, 0xd0, 0x99, 0x79, 0x0b, 0xad, 0x11, 0x24, 0xba, 0x90, 0xd2, 0x55, 0x57,
	0x05, 0x75, 0xe1, 0x07, 0x14, 0x5c, 0x8a, 0xe4, 0x0f, 0x62, 0x7d, 0x88, 0x90, 0x26, 0x31, 0xef,
	0x05, 0xfc, 0x7c, 0xa1, 0x58, 0x95, 0x6e, 0x5c, 0xde, 0x0b, 0x07, 0xce, 0x81, 0xb9, 0x37, 0xba,
	0xc1, 0x16, 0x2d, 0x37, 0xce, 0x72, 0x70, 0xc6, 0x60, 0xa8, 0x7c, 0x70, 0xec, 0x8a, 0x15, 0x8c,
	0x15, 0x92, 0x8b, 0xa1, 0x41, 0x85, 0xd7, 0x88, 0xc4, 0x62, 0x09, 0xa0, 0xbd, 0xaf, 0x9d, 0x65,
	0xbc, 0xb1, 0x4c, 0xf2, 0xa4, 0xfc, 0x57, 0x6f, 0x4f, 0x71, 0x82, 0xec, 0x85, 0x90, 0x77, 0x96,
	0xf0, 0x13, 0x23, 0x66, 0x90, 0x12, 0x6b, 0x8e, 0x24, 0xbf, 0xf3, 0xa4, 0xfc, 0x53, 0x8f, 0x25,
	0x24, 0xfc, 0xb6, 0x48, 0xa4, 0xcf, 0x28, 0x7f, 0x3a, 0xa8, 0x9f, 0xeb, 0x3d, 0x4c, 0x0f, 0xbd,
	0x75, 0xfd, 0xb4, 0x16, 0x5b, 0x18, 0xed, 0x2e, 0x86, 0x31, 0xd4, 0x26, 0x12, 0x63, 0x20, 0x91,
	0x55, 0x83, 0x80, 0xc5, 0xa4, 0x1a, 0xfa, 0x15, 0x5f, 0xc7, 0xb4, 0xeb, 0xdd, 0xdc, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x5a, 0xaf, 0xc2, 0xec, 0x0c, 0x01, 0x00, 0x00,
}
