FROM golang:1.13-alpine

COPY http-client/http-client /app/http-client

WORKDIR /app

EXPOSE 2222

# Install some network tools in the container.
# Packages are listed in alphabetical order, for ease of readability and ease of maintenance.
RUN apk update \
    &&  apk add apache2-utils bash bind-tools busybox-extras curl ethtool git \
                iperf3 iproute2 iputils jq lftp mtr mysql-client \
                netcat-openbsd net-tools nginx nmap openssh-client openssl \
	        perl-net-telnet postgresql-client procps rsync socat tcpdump tshark wget

# Install some run-time build tools in the container.
RUN apk add --no-cache git make py-pip openssl ca-certificates wget bash build-base && update-ca-certificates
RUN apk add --no-cache libc6-compat

ENTRYPOINT ["/app/http-client"]