{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
*/}}
{{- if eq (empty .Values.global.disableDbAuth) true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-configmap
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  mongo-user.sh: |
    mongo -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" <<EOF
    use mco
    db.createUser(
      {
        user: "$DB_EMCO_USERNAME",
        pwd: "$DB_EMCO_PASSWORD",
        roles: [
           { role: "dbOwner", db: "mco" },
           { role: "clusterMonitor", db: "admin" }
        ]
      }
    )
    EOF
{{- end -}}
