{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
*/}}
{{- if eq (empty .Values.global.disableDbAuth) true }}
apiVersion: v1
kind: Secret
metadata:
  name: emco-mongo
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  userPassword: {{ (default (randAlphaNum 10) $.Values.global.db.emcoPassword) | b64enc | quote }}
  rootPassword: {{ (default (randAlphaNum 10) $.Values.global.db.rootPassword) | b64enc | quote }}
{{- end -}}
