// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import module "github.com/open-ness/EMCO/src/dcm/pkg/module"

// UserPermissionManager is an autogenerated mock type for the UserPermissionManager type
type UserPermissionManager struct {
	mock.Mock
}

// CreateUserPerm provides a mock function with given fields: project, logicalCloud, c
func (_m *UserPermissionManager) CreateUserPerm(project string, logicalCloud string, c module.UserPermission) (module.UserPermission, error) {
	ret := _m.Called(project, logicalCloud, c)

	var r0 module.UserPermission
	if rf, ok := ret.Get(0).(func(string, string, module.UserPermission) module.UserPermission); ok {
		r0 = rf(project, logicalCloud, c)
	} else {
		r0 = ret.Get(0).(module.UserPermission)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, module.UserPermission) error); ok {
		r1 = rf(project, logicalCloud, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserPerm provides a mock function with given fields: project, logicalCloud, name
func (_m *UserPermissionManager) DeleteUserPerm(project string, logicalCloud string, name string) error {
	ret := _m.Called(project, logicalCloud, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(project, logicalCloud, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUserPerms provides a mock function with given fields: project, logicalCloud
func (_m *UserPermissionManager) GetAllUserPerms(project string, logicalCloud string) ([]module.UserPermission, error) {
	ret := _m.Called(project, logicalCloud)

	var r0 []module.UserPermission
	if rf, ok := ret.Get(0).(func(string, string) []module.UserPermission); ok {
		r0 = rf(project, logicalCloud)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]module.UserPermission)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, logicalCloud)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPerm provides a mock function with given fields: project, logicalCloud, name
func (_m *UserPermissionManager) GetUserPerm(project string, logicalCloud string, name string) (module.UserPermission, error) {
	ret := _m.Called(project, logicalCloud, name)

	var r0 module.UserPermission
	if rf, ok := ret.Get(0).(func(string, string, string) module.UserPermission); ok {
		r0 = rf(project, logicalCloud, name)
	} else {
		r0 = ret.Get(0).(module.UserPermission)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(project, logicalCloud, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPerm provides a mock function with given fields: project, logicalCloud, name, c
func (_m *UserPermissionManager) UpdateUserPerm(project string, logicalCloud string, name string, c module.UserPermission) (module.UserPermission, error) {
	ret := _m.Called(project, logicalCloud, name, c)

	var r0 module.UserPermission
	if rf, ok := ret.Get(0).(func(string, string, string, module.UserPermission) module.UserPermission); ok {
		r0 = rf(project, logicalCloud, name, c)
	} else {
		r0 = ret.Get(0).(module.UserPermission)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, module.UserPermission) error); ok {
		r1 = rf(project, logicalCloud, name, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
