# Default values for slb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

resources:
  cpu: 1
  memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
