// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/open-ness/EMCO/src/sfcclient/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// SfcManager is an autogenerated mock type for the SfcManager type
type SfcManager struct {
	mock.Mock
}

// CreateSfcClientIntent provides a mock function with given fields: sfc, pr, ca, caver, dig, netctrlint, exists
func (_m *SfcManager) CreateSfcClientIntent(sfc model.SfcClientIntent, pr string, ca string, caver string, dig string, netctrlint string, exists bool) (model.SfcClientIntent, error) {
	ret := _m.Called(sfc, pr, ca, caver, dig, netctrlint, exists)

	var r0 model.SfcClientIntent
	if rf, ok := ret.Get(0).(func(model.SfcClientIntent, string, string, string, string, string, bool) model.SfcClientIntent); ok {
		r0 = rf(sfc, pr, ca, caver, dig, netctrlint, exists)
	} else {
		r0 = ret.Get(0).(model.SfcClientIntent)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.SfcClientIntent, string, string, string, string, string, bool) error); ok {
		r1 = rf(sfc, pr, ca, caver, dig, netctrlint, exists)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSfcClientIntent provides a mock function with given fields: name, pr, ca, caver, dig, netctrlint
func (_m *SfcManager) DeleteSfcClientIntent(name string, pr string, ca string, caver string, dig string, netctrlint string) error {
	ret := _m.Called(name, pr, ca, caver, dig, netctrlint)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string) error); ok {
		r0 = rf(name, pr, ca, caver, dig, netctrlint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllSfcClientIntents provides a mock function with given fields: pr, ca, caver, dig, netctrlint
func (_m *SfcManager) GetAllSfcClientIntents(pr string, ca string, caver string, dig string, netctrlint string) ([]model.SfcClientIntent, error) {
	ret := _m.Called(pr, ca, caver, dig, netctrlint)

	var r0 []model.SfcClientIntent
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) []model.SfcClientIntent); ok {
		r0 = rf(pr, ca, caver, dig, netctrlint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SfcClientIntent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(pr, ca, caver, dig, netctrlint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSfcClientIntent provides a mock function with given fields: name, pr, ca, caver, dig, netctrlint
func (_m *SfcManager) GetSfcClientIntent(name string, pr string, ca string, caver string, dig string, netctrlint string) (model.SfcClientIntent, error) {
	ret := _m.Called(name, pr, ca, caver, dig, netctrlint)

	var r0 model.SfcClientIntent
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string) model.SfcClientIntent); ok {
		r0 = rf(name, pr, ca, caver, dig, netctrlint)
	} else {
		r0 = ret.Get(0).(model.SfcClientIntent)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string) error); ok {
		r1 = rf(name, pr, ca, caver, dig, netctrlint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
