# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitor
subjects:
- kind: ServiceAccount
  name: monitor
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: monitor
  apiGroup: rbac.authorization.k8s.io