// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	module "github.com/open-ness/EMCO/src/dtc/pkg/module"
	mock "github.com/stretchr/testify/mock"
)

// TrafficGroupIntentManager is an autogenerated mock type for the TrafficGroupIntentManager type
type TrafficGroupIntentManager struct {
	mock.Mock
}

// CreateTrafficGroupIntent provides a mock function with given fields: tci, project, compositeapp, compositeappversion, deploymentIntentGroupName, exists
func (_m *TrafficGroupIntentManager) CreateTrafficGroupIntent(tci module.TrafficGroupIntent, project string, compositeapp string, compositeappversion string, deploymentIntentGroupName string, exists bool) (module.TrafficGroupIntent, error) {
	ret := _m.Called(tci, project, compositeapp, compositeappversion, deploymentIntentGroupName, exists)

	var r0 module.TrafficGroupIntent
	if rf, ok := ret.Get(0).(func(module.TrafficGroupIntent, string, string, string, string, bool) module.TrafficGroupIntent); ok {
		r0 = rf(tci, project, compositeapp, compositeappversion, deploymentIntentGroupName, exists)
	} else {
		r0 = ret.Get(0).(module.TrafficGroupIntent)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(module.TrafficGroupIntent, string, string, string, string, bool) error); ok {
		r1 = rf(tci, project, compositeapp, compositeappversion, deploymentIntentGroupName, exists)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTrafficGroupIntent provides a mock function with given fields: name, project, compositeapp, compositeappversion, dig
func (_m *TrafficGroupIntentManager) DeleteTrafficGroupIntent(name string, project string, compositeapp string, compositeappversion string, dig string) error {
	ret := _m.Called(name, project, compositeapp, compositeappversion, dig)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) error); ok {
		r0 = rf(name, project, compositeapp, compositeappversion, dig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTrafficGroupIntent provides a mock function with given fields: name, project, compositeapp, compositeappversion, dig
func (_m *TrafficGroupIntentManager) GetTrafficGroupIntent(name string, project string, compositeapp string, compositeappversion string, dig string) (module.TrafficGroupIntent, error) {
	ret := _m.Called(name, project, compositeapp, compositeappversion, dig)

	var r0 module.TrafficGroupIntent
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) module.TrafficGroupIntent); ok {
		r0 = rf(name, project, compositeapp, compositeappversion, dig)
	} else {
		r0 = ret.Get(0).(module.TrafficGroupIntent)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(name, project, compositeapp, compositeappversion, dig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTrafficGroupIntents provides a mock function with given fields: project, compositeapp, compositeappversion, dig
func (_m *TrafficGroupIntentManager) GetTrafficGroupIntents(project string, compositeapp string, compositeappversion string, dig string) ([]module.TrafficGroupIntent, error) {
	ret := _m.Called(project, compositeapp, compositeappversion, dig)

	var r0 []module.TrafficGroupIntent
	if rf, ok := ret.Get(0).(func(string, string, string, string) []module.TrafficGroupIntent); ok {
		r0 = rf(project, compositeapp, compositeappversion, dig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]module.TrafficGroupIntent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(project, compositeapp, compositeappversion, dig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
