{{- if and (empty .Values.global.disableDbAuth) (and .Values.auth.rbac.enabled (not .Values.auth.rbac.existingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: emco-etcd
  labels: {{- include "etcd.labels" . | nindent 4 }}
type: Opaque
data:
  etcd-root-password: {{ (default (randAlphaNum 10) $.Values.global.contextdb.rootPassword) | b64enc | quote }}
{{- end }}
